config/routes.rb
Rails.application.routes.draw do
  resources :violation_reports
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "violation_reports#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/violation_report.rb
class ViolationReport < ApplicationRecord
  validates :vehicle_count, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/violation_reports_controller.rb
class ViolationReportsController < ApplicationController
  before_action :set_violation_report, only: %i[ show edit update destroy ]

  # GET /violation_reports or /violation_reports.json
  def index
    @violation_reports = ViolationReport.all
  end

  # GET /violation_reports/1 or /violation_reports/1.json
  def show
  end

  # GET /violation_reports/new
  def new
    @violation_report = ViolationReport.new
  end

  # GET /violation_reports/1/edit
  def edit
  end

  # POST /violation_reports or /violation_reports.json
  def create
    @violation_report = ViolationReport.new(violation_report_params)

    respond_to do |format|
      if @violation_report.save
        format.html { redirect_to @violation_report, notice: "Violation report was successfully created." }
        format.json { render :show, status: :created, location: @violation_report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @violation_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /violation_reports/1 or /violation_reports/1.json
  def update
    respond_to do |format|
      if @violation_report.update(violation_report_params)
        format.html { redirect_to @violation_report, notice: "Violation report was successfully updated." }
        format.json { render :show, status: :ok, location: @violation_report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @violation_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /violation_reports/1 or /violation_reports/1.json
  def destroy
    @violation_report.destroy!

    respond_to do |format|
      format.html { redirect_to violation_reports_path, status: :see_other, notice: "Violation report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_violation_report
      @violation_report = ViolationReport.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def violation_report_params
      params.expect(violation_report: [ :vehicle_count, :latitude, :longitude ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/violation_reports_helper.rb
module ViolationReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Khonreep" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/violation_reports/_form.html.erb
<%= form_with(model: violation_report, class: "contents") do |form| %>
  <% if violation_report.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(violation_report.errors.count, "error") %> prohibited this violation_report from being saved:</h2>

      <ul class="list-disc ml-6">
        <% violation_report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :vehicle_count %>
    <%= form.number_field :vehicle_count, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": violation_report.errors[:vehicle_count].none?, "border-red-400 focus:outline-red-600": violation_report.errors[:vehicle_count].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": violation_report.errors[:latitude].none?, "border-red-400 focus:outline-red-600": violation_report.errors[:latitude].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": violation_report.errors[:longitude].none?, "border-red-400 focus:outline-red-600": violation_report.errors[:longitude].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/violation_reports/_violation_report.html.erb
<div id="<%= dom_id violation_report %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Vehicle count:</strong>
    <%= violation_report.vehicle_count %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Latitude:</strong>
    <%= violation_report.latitude %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Longitude:</strong>
    <%= violation_report.longitude %>
  </div>
</div>

app/views/violation_reports/edit.html.erb
<% content_for :title, "Editing violation report" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing violation report</h1>

  <%= render "form", violation_report: @violation_report %>

  <%= link_to "Show this violation report", @violation_report, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to violation reports", violation_reports_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/violation_reports/index.html.erb
<% content_for :title, "Violation reports" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Violation reports</h1>
    <%= link_to "New violation report", new_violation_report_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="violation_reports" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @violation_reports.any? %>
      <% @violation_reports.each do |violation_report| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render violation_report %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", violation_report, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_violation_report_path(violation_report), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", violation_report, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No violation reports found.</p>
    <% end %>
  </div>
</div>

app/views/violation_reports/new.html.erb
<% content_for :title, "Red Light Violations 🚦" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Red Light Violation 🚗</h1>
  <button id="report-btn" type="button" class="w-full h-1/2 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-xl px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
    Count it!
  </button>
  <p id="status-msg"></p>
  <p id="position-value"></p>
</div>

<script>
document.addEventListener("DOMContentLoaded", () => {
  const btn = document.getElementById("report-btn");
  const status = document.getElementById("status-msg");
  const positionValue = document.getElementById("position-value");

  btn.addEventListener("click", () => {
    if (!navigator.geolocation) {
      status.textContent = "Geolocation is not supported by your browser.";
      return;
    }

    navigator.geolocation.getCurrentPosition(position => {
      console.log(position.coords.latitude, position.coords.longitude)
      positionValue.textContent = position.coords.latitude + ", " + position.coords.longitude
      // fetch("/violations", {
      //   method: "POST",
      //   headers: {
      //     "Content-Type": "application/json",
      //     "X-CSRF-Token": document.querySelector('meta[name="csrf-token"]').content
      //   },
      //   body: JSON.stringify({
      //     violation: {
      //       latitude: position.coords.latitude,
      //       longitude: position.coords.longitude
      //     }
      //   })
      // })
      // .then(response => {
      //   if (response.ok) {
      //     status.textContent = "🚨 Violation reported!";
      //     location.reload(); // Optional: update the list
      //   } else {
      //     status.textContent = "❌ Failed to report.";
      //   }
      // })
      // .catch(error => {
      //   console.error(error);
      //   status.textContent = "❌ Error reporting violation.";
      // });
    });
  });
});
</script>

app/views/violation_reports/show.html.erb
<% content_for :title, "Showing violation report" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing violation report</h1>

  <%= render @violation_report %>

  <%= link_to "Edit this violation report", edit_violation_report_path(@violation_report), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to violation reports", violation_reports_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this violation report", @violation_report, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>